# Generated by Django 5.1.3 on 2024-12-01 06:24

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to=core.models.custom_upload_to),
        ),
    ]
