name: Sourcery

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sourcery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Sourcery
        uses: sourcery-ai/sourcery-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
